name: Deploy Invoice

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, curl, dom, fileinfo, openssl, pdo, tokenizer, xml
    - name: Install dependencies
      run: |
        composer install --no-dev --optimize-autoloader
        npm ci
        npm run build
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Update .env for Database
      run: |
        sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=${{ env.DB_CONNECTION }}/' .env
        sed -i 's/^DB_DATABASE=.*/DB_DATABASE=${{ env.DB_DATABASE }}/' .env
        sed -i 's/^DB_HOST=.*/DB_HOST=${{ env.DB_HOST }}/' .env
        sed -i 's/^DB_PORT=.*/DB_PORT=${{ env.DB_PORT }}/' .env
        sed -i 's/^DB_USERNAME=.*/DB_USERNAME=${{ env.DB_USERNAME }}/' .env
        sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=${{ env.DB_PASSWORD }}/' .env
        sed -i 's/^MAIL_USERNAME=.*/MAIL_USERNAME=${{ env.MAIL_USERNAME}}/' .env
        sed -i 's/^MAIL_FROM_ADDRESS=.*/MAIL_FROM_ADDRESS=${{ env.MAIL_FROM_ADDRESS}}/' .env

    - name: Set permissions
      run: |
        chmod -R 775 storage bootstrap/cache
        chown -R www-data:www-data .

    - name: Laravel Migrate & Cache
      run: |
        php artisan migrate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
    - name: Deploy New Version
      run: |
        NEW_RELEASE_DIR=/var/www/invoice/releases/$(date +%Y%m%d%H%M%S)
        echo "$PASSWORD_SERVER" | sudo -S mkdir -p $NEW_RELEASE_DIR
        echo "$PASSWORD_SERVER" | sudo -S rsync -av --exclude=.git --exclude=node_modules . $NEW_RELEASE_DIR
        echo "$PASSWORD_SERVER" | sudo -S ln -sfn $NEW_RELEASE_DIR /var/www/invoice/current
        echo "$PASSWORD_SERVER" | sudo -S chown -R www-data:www-data /var/www/invoice
    - name: Restart PHP & Clear OPcache
      run: |
        sudo systemctl restart php8.2-fpm
        sudo systemctl reload nginx
